library movies;

// datasources
export 'package:movies/data/datasources/movie_local_data_source.dart';
export 'package:movies/data/datasources/movie_remote_data_source.dart';
// models
export 'package:movies/data/models/genre_model.dart';
export 'package:movies/data/models/movie_detail_model.dart';
export 'package:movies/data/models/movie_model.dart';
export 'package:movies/data/models/movie_response.dart';
export 'package:movies/data/models/movie_table.dart';
// repositories
export 'package:movies/data/repositories/movie_repository_impl.dart';
// entities
export 'package:movies/domain/entities/genre.dart';
export 'package:movies/domain/entities/movie_detail.dart';
export 'package:movies/domain/entities/movie.dart';
export 'package:ditonton/domain/entities/watchlist.dart';
// domain repositories
export 'package:movies/domain/repositories/movie_repository.dart';
// usecases
export 'package:movies/domain/usecases/get_movie_detail.dart';
export 'package:movies/domain/usecases/get_movie_recommendations.dart';
export 'package:movies/domain/usecases/get_now_playing_movies.dart';
export 'package:movies/domain/usecases/get_popular_movies.dart';
export 'package:movies/domain/usecases/get_top_rated_movies.dart';
export 'package:movies/domain/usecases/search_movies.dart';
// blocs
export 'package:movies/presentation/blocs/detail/detail_bloc.dart';
export 'package:movies/presentation/blocs/now_playing/now_playing_bloc.dart';
export 'package:movies/presentation/blocs/popular/popular_bloc.dart';
export 'package:movies/presentation/blocs/search/search_bloc.dart';
export 'package:movies/presentation/blocs/top_rated/top_rated_bloc.dart';

// pages
export 'package:movies/presentation/pages/home_movie_page.dart';
export 'package:movies/presentation/pages/movie_detail_page.dart';
export 'package:movies/presentation/pages/popular_movies_page.dart';
export 'package:movies/presentation/pages/search_movie_page.dart';
export 'package:movies/presentation/pages/top_rated_movies_page.dart';
// widgets
export 'package:movies/presentation/widgets/movie_card_list.dart';
